In [1]:
import wandb
import torch
import torch.nn as nn
from torch.utils.data import Dataset
import torchvision.transforms as T
from PIL import Image
import matplotlib.pyplot as plt
import gc
import os.path

import net_config as cfg
%run models.ipynb
%run trainer.ipynb

C:\Users\matul\Desktop\NSIETE\zadanie2\pvtv2.py:386: UserWarning: Overwriting pvt_v2_b0 in registry with pvtv2.pvt_v2_b0. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  @register_model
C:\Users\matul\Desktop\NSIETE\zadanie2\pvtv2.py:396: UserWarning: Overwriting pvt_v2_b1 in registry with pvtv2.pvt_v2_b1. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  @register_model
C:\Users\matul\Desktop\NSIETE\zadanie2\pvtv2.py:404: UserWarning: Overwriting pvt_v2_b2 in registry with pvtv2.pvt_v2_b2. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  @register_model
C:\Users\matul\Desktop\NSIETE\zadanie2\pvtv2.py:412: UserWarning: Overwriting pvt_v2_b3 in registry with pvtv2.pvt_v2_b3. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  @reg

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]], dtype=torch.int32)


In [2]:
class Lizard_dataset(Dataset):
    def __init__(self, path_images, path_labels):
        self.images = []
        self.labels = []
        self.transform = T.ToPILImage()

        self.class_colors = torch.FloatTensor([
            [0, 0, 0]           #black
            , [30, 144, 255]    #dodger blue
            , [220, 20, 60]     #crimson
            , [34, 139, 34]     #forest green
            , [238, 130, 238]   #violet
            , [255, 255, 0]     #yellow
            , [211, 211, 211]   #gainsboro
            ]
        )

        # Load images and labels as tensors to cpu (moved to gpu during training)
        self.images = torch.load(path_images, map_location="cpu").type(torch.float32)
        self.labels = torch.load(path_labels, map_location="cpu").type(torch.int64)

        #print(self.images.dtype)
        #print(self.labels.dtype)

        img_count = self.images.size(dim=0)
        num_channels = self.images.size(dim=1)
        height = self.images.size(dim=2)
        width = self.images.size(dim=3)

        img_count2 = self.labels.size(dim=0)
        height2 = self.labels.size(dim=1)
        width2 = self.labels.size(dim=2)

        assert img_count == img_count2, f"Wrong IMAGE COUNT for dataset: images = {img_count} | labels = {img_count2}"
        assert height == height2, f"Wrong image HEIGHT for dataset: images = {height} | labels = {height2}"
        assert width == width2, f"Wrong image WIDTH for dataset: images = {width} | labels = {width2}"
        assert num_channels == 3, f"Wrong image CHANNEL COUNT for dataset: images = {num_channels} | needed = 3"
        
    def __len__(self):
        return self.images.size(dim=0)

    def __getitem__(self, idx):
        image = self.images[idx, :, :, :]
        label = self.labels[idx, :, :]
        #image = torch.unsqueeze(image, dim= 0)
        #label = torch.unsqueeze(label, dim= 0)

        return (image, label)
    
    def show_imgLabel(self, idx):
        img_t, label_t = self.__getitem__(idx)

        # Show image
        image = self.transform(img_t)

        plt.figure(figsize=(8, 8))
        plt.imshow(image)
        plt.title(f'Original Image  with index = {idx}')
        plt.axis('off')
        plt.show()

        # show segmentation
        converted_tensor = torch.nn.functional.embedding(label_t.type(torch.int64), self.class_colors).permute(2, 0, 1)
        colormap = self.transform(converted_tensor)

        # show segmentation
        plt.figure(figsize=(8, 8))
        plt.imshow(colormap)
        plt.title('Segmentation Heatmap')
        plt.axis('off')
        plt.show()

    def show_tensorImg(self, t):
        t = torch.squeeze(t)
        img = self.transform(t)
        plt.show(img)
        

In [3]:
class wanDB_run: 
    def __init__(self, run_name, run_id, model: nn.Module, save_interval = None):
        wandb.login()
        assert wandb.run is None, "wanDB has another run currently active"
        
        self.run = wandb.init(
        entity = cfg.project_entity, 
        project = cfg.project_name,     
        name = run_name, 
        id = run_id
        )

        wandb.config = cfg.config_to_dict(cfg.config_Unet)

        self.trainer = Trainer(model)
        self.save_interval = save_interval
        self.datasets_loaded = False

        # Load best model
        if (self.save_interval is not None) and os.path.isfile(cfg.model_path):
            self.current_epoch = self.trainer.load_model()
        else:
            self.current_epoch = 0

    def load_datasets(self, train_pathX, train_pathY, val_pathX, val_pathY, test_pathX, test_pathY):
        trainData = Lizard_dataset(train_pathX, train_pathY)
        valData = Lizard_dataset(val_pathX, val_pathY)
        testData = Lizard_dataset(test_pathX, test_pathY)

        self.trainer.load_dataset(trainData, valData, testData)
        self.datasets_loaded = True
    
    def execute_training(self, epoch_count):
        assert self.datasets_loaded, "Datasets are NOT loaded"

        for _ in range(epoch_count):
            self.current_epoch += 1
            print(f"--Starting epoch {self.current_epoch}--")

            # Train model
            self.trainer.train_model()
            # Evaluate model
            self.trainer.evaluate_model()

            # Get metrics
            tl = self.trainer.stats.metric_average(cfg.metric_name_Tloss)
            vl = self.trainer.stats.metric_average(cfg.metric_name_Vloss)
            acc = self.trainer.stats.metric_average(cfg.metric_name_acc)
            iou = self.trainer.stats.metric_average(cfg.metric_name_IoU)
            dice = self.trainer.stats.metric_average(cfg.metric_name_dice)

            # Save metrics to wandb
            self.run.log({"loss_train": tl, "epoch": self.current_epoch})
            self.run.log({"loss_val": vl, "epoch": self.current_epoch})
            self.run.log({"accuracy": acc, "epoch": self.current_epoch})
            self.run.log({"iou": iou, "epoch": self.current_epoch})
            self.run.log({"dice": dice, "epoch": self.current_epoch})

            # Save best model
            if (self.save_interval is not None) and (self.current_epoch % self.save_interval == 0):
                self.trainer.save_model(self.current_epoch)

            print(f"--Ending epoch {self.current_epoch}--")
    
    def stop_run(self):
        self.run.finish()
        del self.trainer
        self.datasets_loaded = False

        gc.collect()


In [4]:
%env "WANDB_NOTEBOOK_NAME" "NN"
wandb.login()
wandb.finish()

save_interval = 3

env: "WANDB_NOTEBOOK_NAME"="NN"


Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.
wandb: Currently logged in as: matus13579 (mteam0). Use `wandb login --relogin` to force relogin


In [5]:
netv2 = UNetV2(cfg.num_of_classes, cfg.config_to_dict(cfg.config_Unet))

myrun = wanDB_run("testuv2", "2", netv2, 3)

myrun.load_datasets(
    cfg.data_dir + "X_train.pt"
    , cfg.data_dir + "y_train.pt" 
    , cfg.data_dir + "X_val.pt"
    , cfg.data_dir + "y_val.pt"
    , cfg.data_dir + "X_test.pt"
    , cfg.data_dir + "y_test.pt"
)

wandb: Currently logged in as: matus13579. Use `wandb login --relogin` to force relogin


Using cpu device for training


In [6]:
myrun.execute_training(3)

--Starting epoch 1--
torch.Size([4, 64, 125, 125])
torch.Size([4, 128, 63, 63])
torch.Size([4, 320, 32, 32])
torch.Size([4, 512, 16, 16])
------
torch.Size([4, 32, 125, 125])
torch.Size([4, 32, 63, 63])
torch.Size([4, 32, 32, 32])
torch.Size([4, 32, 16, 16])
------
torch.Size([4, 32, 16, 16])
torch.Size([4, 32, 32, 32])
torch.Size([4, 32, 63, 63])
torch.Size([4, 32, 125, 125])
------
torch.Size([4, 32, 32, 32])
torch.Size([4, 32, 32, 32])
torch.Size([4, 7, 32, 32])
torch.Size([4, 32, 64, 64])
torch.Size([4, 32, 63, 63])


RuntimeError: The size of tensor a (64) must match the size of tensor b (63) at non-singleton dimension 3

In [ ]:
#myrun.stop_run()
wandb.finish()